#!/usr/bin/env python3
"""MEASURE the reducible span at a given rank, instead of hand-counting it.

WHY THIS EXISTS AS A COMMITTED SCRIPT. Every "irreducible = 0" headline we have is a SUBTRACTION:
dim(solution) - dim(reducible). The first half is measured by the prover over GF(p). The second
half was, until now, produced by hand and re-derived in throwaway heredocs -- and it has been
WRONG THREE TIMES (22, 30, and 10 against truths of 33 and higher). The load-bearing half of the
claim was the unversioned half. That is the bug.

WHAT IT MEASURES, AND WHY THE GENERATOR LIST IS NOT AN ASSUMPTION. The reducible span at degree r
is the degree-r part of the ring generated by the lower-degree conserved quantities. We supply
candidate generators, but every one is CHECKED with an exact {H, g} = 0 before it is used, and the
resulting counts are CROSS-CHECKED against independently measured solution dimensions at the low
ranks. If the generator set were incomplete, those low ranks would disagree. Rank 1/2/3 agreeing
and rank 5 disagreeing means something specific, and it is not "we found irreducible tensors".

Repro:  .venv/bin/python scripts/_kt_reducible.py <delta> <rank_max>
"""
import os
import sys
import time
import itertools
import random

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sympy as sp
import _kt_zv as ZV

t, x, y, ph = sp.symbols("t x y phi", real=True)
Pt, Px, Py, Pph = sp.symbols("P_t P_x P_y P_phi", real=True)
CO = (t, x, y, ph)
MO = (Pt, Px, Py, Pph)


def poisson(F, G):
    return sum(sp.diff(F, MO[i]) * sp.diff(G, CO[i]) - sp.diff(F, CO[i]) * sp.diff(G, MO[i])
               for i in range(4))


def main():
    delta = int(sys.argv[1])
    rmax = int(sys.argv[2])
    ginv = ZV.zv_inv(delta)
    H = sum(ginv[i, j] * MO[i] * MO[j] for i in range(4) for j in range(4))
    H = sp.cancel(sp.together(H))

    # CANDIDATE generators. p_t and p_phi are the manifest Killing vectors. H is the Hamiltonian.
    # Lsq is Schwarzschild's total angular momentum, written in prolate spheroidal coordinates
    # (y = cos theta, so p_theta = -sin(theta) p_y and sin^2 = 1 - y^2). It is NOT manifest as a
    # rank-1 solution here -- L_x and L_y are not axisymmetric and fall outside the ansatz -- but
    # its square IS axisymmetric, which is exactly why a hand-count over {p_t, p_phi, H} misses it.
    Lsq = (1 - y**2) * Py**2 + Pph**2 / (1 - y**2)
    cands = [("p_t", Pt, 1), ("p_phi", Pph, 1), ("H", H, 2), ("Lsq", Lsq, 2)]

    print(f"ZV delta={delta}: CHECKING each candidate generator with an exact Poisson bracket",
          flush=True)
    gens = []
    for nm, g, dg in cands:
        pb = sp.cancel(sp.together(sp.expand(poisson(H, g))))
        ok = (pb == 0)
        print(f"    {nm:6s} degree {dg}   {{H,g}} = 0 exactly: {'YES' if ok else 'NO'}", flush=True)
        if ok:
            gens.append((nm, g, dg))
    # KNOWN-FAIL: a quantity that is NOT conserved must be rejected by the same check, or the
    # check is not checking (rule 1 -- a criterion with no known-fail gates nothing).
    bad = Pt**2 * Px * Py
    pbb = sp.cancel(sp.together(sp.expand(poisson(H, bad))))
    print(f"    KNOWN-FAIL p_t^2 p_x p_y: {{H,g}} = 0: {'YES  <-- CHECK IS BROKEN' if pbb == 0 else 'NO (correctly rejected)'}",
          flush=True)

    # Enumerate every monomial in the surviving generators of total degree exactly r.
    rng = random.Random(20260821)
    pts = []
    for _ in range(60):
        sub = {t: sp.Rational(rng.randint(1, 40), rng.randint(1, 17)),
               x: sp.Rational(rng.randint(3, 60), rng.randint(1, 7)),
               y: sp.Rational(rng.randint(1, 30), rng.randint(37, 61)),
               ph: sp.Rational(rng.randint(1, 40), rng.randint(1, 17))}
        for m in MO:
            sub[m] = sp.Rational(rng.randint(-50, 50), rng.randint(1, 13))
        pts.append(sub)

    for r in range(1, rmax + 1):
        monos = []
        degs = [d for _, _, d in gens]
        for expo in itertools.product(*[range(r // d + 1) for d in degs]):
            if sum(e * d for e, d in zip(expo, degs)) != r:
                continue
            lab = "*".join(f"{gens[i][0]}^{e}" for i, e in enumerate(expo) if e)
            val = sp.Integer(1)
            for i, e in enumerate(expo):
                if e:
                    val *= gens[i][1]**e
            monos.append((lab, val))
        if not monos:
            print(f"  rank {r}: no products of this degree", flush=True)
            continue
        t0 = time.time()
        rows = []
        for sub in pts:
            rows.append([v.subs(sub) for _, v in monos])
        M = sp.Matrix(rows)
        rk = M.rank()
        assert M.shape == (len(pts), len(monos)), f"SHAPE {M.shape} vs {(len(pts), len(monos))}"
        print(f"  rank {r}: {len(monos):3d} products spanning a space of MEASURED DIMENSION {rk}"
              f"   [{time.time()-t0:.1f}s]", flush=True)
        if rk < len(monos):
            print(f"           ({len(monos)-rk} algebraic relations among the products)", flush=True)


# ---------------------------------------------------------------------------------------------
# REPRESENTABILITY: which reducibles can the den^1 ansatz actually HOLD?
#
# WHY THIS IS A SEPARATE QUESTION. dim(reducible) <= dim(solution) is an impossibility only when
# both sides are counted in the SAME space. The prover's solution space is the set of Killing
# tensors expressible as (polynomial of bounded degree)/L -- one power of the denominator. The
# reducible span is a fact about the spacetime and knows nothing about L. So the honest comparison
# is against dim(reducible AND representable), and the excluded ones must be identified by
# CONSTRUCTION, not waved at. A product of two degree-2 generators carries L^2 and drops out.
#
# Repro:  .venv/bin/python scripts/_kt_reducible.py <delta> <rank_max> --representable
# ---------------------------------------------------------------------------------------------

def _rank_at_points(exprs, primes, seed=20260822):
    """Rank of a set of phase-space functions, measured over GF(p) at random integer points.

    Rational evaluation is exact but the numerators explode past degree 4 -- a 60x20 rank took
    almost an hour. Reducing each evaluated Rational mod p keeps every entry a machine word.
    Two primes, because a single prime can drop rank by bad luck; agreement is the check."""
    if not exprs:
        return 0
    n = len(exprs)
    rng = random.Random(seed)
    ranks = []
    for p in primes:
        rows = []
        for _ in range(n + 8):
            sub = {t: rng.randint(2, 97), x: rng.randint(3, 89), y: sp.Rational(rng.randint(1, 30), 61),
                   ph: rng.randint(2, 97)}
            for m in MO:
                sub[m] = rng.randint(-60, 60)
            row = []
            bad = False
            for e in exprs:
                v = sp.nsimplify(e.subs(sub))
                num, den = sp.fraction(sp.cancel(v))
                num, den = int(num), int(den)
                if den % p == 0:
                    bad = True
                    break
                row.append(num % p * pow(den, -1, p) % p)
            if not bad:
                rows.append(row)
        # Gaussian elimination over GF(p)
        rk = 0
        for col in range(n):
            piv = next((i for i in range(rk, len(rows)) if rows[i][col] % p), None)
            if piv is None:
                continue
            rows[rk], rows[piv] = rows[piv], rows[rk]
            inv = pow(rows[rk][col], -1, p)
            rows[rk] = [v * inv % p for v in rows[rk]]
            for i in range(len(rows)):
                if i != rk and rows[i][col]:
                    f = rows[i][col]
                    rows[i] = [(a - f * b) % p for a, b in zip(rows[i], rows[rk])]
            rk += 1
        ranks.append(rk)
    assert ranks[0] == ranks[1], f"primes disagree on rank: {ranks}"
    return ranks[0]


def representable():
    delta = int(sys.argv[1])
    rmax = int(sys.argv[2])
    ginv = ZV.zv_inv(delta)
    H = sp.cancel(sp.together(sum(ginv[i, j] * MO[i] * MO[j] for i in range(4) for j in range(4))))
    Lsq = (1 - y**2) * Py**2 + Pph**2 / (1 - y**2)

    dens = set()
    for i in range(4):
        for j in range(4):
            if ginv[i, j] != 0:
                d = sp.denom(sp.together(ginv[i, j]))
                if d != 1:
                    dens.add(d)
    L = sp.Integer(1)
    for d in dens:
        L = sp.lcm(L, d)
    L = sp.factor(L)
    pL = sp.Poly(sp.expand(L), x, y)
    nx = ny = 0
    for i in range(4):
        for j in range(i, 4):
            if ginv[i, j] != 0:
                pN = sp.Poly(sp.expand(sp.cancel(sp.together(ginv[i, j]) * L)), x, y)
                nx, ny = max(nx, pN.degree(x)), max(ny, pN.degree(y))
    dx, dy = max(pL.degree(x), nx) + 2, max(pL.degree(y), ny) + 2
    print(f"ZV delta={delta}: ansatz is (poly x<={dx}, y<={dy}) / L, with L of "
          f"x-deg {pL.degree(x)}, y-deg {pL.degree(y)}", flush=True)

    gens = [("p_t", Pt, 1), ("p_phi", Pph, 1), ("H", H, 2)]
    if sp.cancel(sp.together(sp.expand(poisson(H, Lsq)))) == 0:
        gens.append(("Lsq", Lsq, 2))
    degs = [d for _, _, d in gens]

    for r in range(1, rmax + 1):
        tot = ok = 0
        dropped = []
        keep = []
        for expo in itertools.product(*[range(r // d + 1) for d in degs]):
            if sum(e * d for e, d in zip(expo, degs)) != r:
                continue
            tot += 1
            lab = "*".join(f"{gens[i][0]}^{e}" if e > 1 else gens[i][0]
                           for i, e in enumerate(expo) if e)
            val = sp.Integer(1)
            for i, e in enumerate(expo):
                if e:
                    val *= gens[i][1]**e
            # expand in the momentum monomials and test each coefficient for (deg<=dx,dy)/L form
            pol = sp.Poly(sp.expand(val), *MO)
            fits = True
            for coeff in pol.coeffs():
                c = sp.cancel(sp.together(coeff))
                num, den = sp.fraction(c)
                q = sp.cancel(sp.together(L / den))
                if sp.denom(q) != 1:                      # den does not divide L -> needs L^2+
                    fits = False
                    break
                nn = sp.Poly(sp.expand(num * q), x, y)
                if nn.degree(x) > dx or nn.degree(y) > dy:
                    fits = False
                    break
            if fits:
                ok += 1
                keep.append(val)
            else:
                dropped.append(lab)
        # COUNTING THE REPRESENTABLE PRODUCTS IS NOT ENOUGH -- they have to be INDEPENDENT.
        # If two of them were linearly dependent, the span would be smaller than the count, the
        # prover's dimension would exceed it, and the surplus would read as an irreducible tensor.
        # So measure the rank of the representable set itself, over GF(p) at random integer points
        # (two primes; exact rationals blow up past rank 4 and take minutes per rank).
        rk = _rank_at_points(keep, (2147483647, 2147483629))
        flag = "" if rk == ok else f"   <-- {ok - rk} RELATION(S), span is only {rk}"
        print(f"  rank {r}: {tot:3d} reducible products, {ok:3d} REPRESENTABLE in the den^1 ansatz,"
              f" independent rank {rk}{flag}", flush=True)
        if dropped:
            print(f"           dropped ({len(dropped)}): {', '.join(dropped)}", flush=True)


if "--representable" in sys.argv:
    representable()
    sys.exit(0)


if __name__ == "__main__":
    main()
